services:
  - type: web
    name: yaml-tag-generator
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 18.x